export interface Customer {
TIPO_REPRESENTANTE?: string;
CEDULA_REPRESENTANTE?: number;
NOMBRES_REPRESENTANTE?: string;
DIRECCION_REPRESENTANTE?: string;
TELEFONO_REPRESENTANTE?: string;
CORREO_REPRESENTANTE?: string;
TIPO_CLIENTE?: string;
ID_CLIENTE?: number;
NOMBRES_CLIENTE?: string;
DIRECCION_CLIENTE?: string;
TELEFONO_CLIENTE?: string;
CORREO_CLIENTE?: string;
FECHA_REGISTRO?: Date;
REGISTRADO_POR?: string;
}